name: Deploy

on:
  push:
    branches: ["master"]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1
